apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::126339536834:role/eks-irsa-role

# dont forget to update acccount id arn:aws:iam::<ACCOUNT_ID>:role/eks-irsa-role
